// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projekt_zaliczeniowy;

#nullable disable

namespace Projekt_zaliczeniowy.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260718010336_DodanieCzyAdmin")]
    partial class DodanieCzyAdmin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Projekt_zaliczeniowy.Uzytkownik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CzyAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HasloHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Uzytkownicy");
                });

            modelBuilder.Entity("Projekt_zaliczeniowy.Wynik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaksymalnaSeria")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UzytkownikId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UzytkownikId")
                        .IsUnique();

                    b.ToTable("Wyniki");
                });

            modelBuilder.Entity("Projekt_zaliczeniowy.Wynik", b =>
                {
                    b.HasOne("Projekt_zaliczeniowy.Uzytkownik", "Uzytkownik")
                        .WithOne("Wynik")
                        .HasForeignKey("Projekt_zaliczeniowy.Wynik", "UzytkownikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uzytkownik");
                });

            modelBuilder.Entity("Projekt_zaliczeniowy.Uzytkownik", b =>
                {
                    b.Navigation("Wynik");
                });
#pragma warning restore 612, 618
        }
    }
}
